version: '3'

services:
  react-web-app:
    image: sungwoo166/react-app:latest
    container_name: react-web-app
    ports:
      - "5173:5173"
    networks:
      - my_network

  springboot-web-service:
    image: sungwoo166/spring-app:latest
    container_name: springboot-web-service
    ports:
      - "8080:8080"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react-web-app
      - springboot-web-service
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
